TRUNCATE TABLE structure_element RESTART IDENTITY CASCADE;
TRUNCATE TABLE position RESTART IDENTITY CASCADE;
TRUNCATE TABLE person RESTART IDENTITY CASCADE;
TRUNCATE TABLE employee RESTART IDENTITY CASCADE;
TRUNCATE TABLE position_assignment RESTART IDENTITY CASCADE;
TRUNCATE TABLE person_absence RESTART IDENTITY CASCADE;
