SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE person_absence RESTART IDENTITY;
TRUNCATE TABLE position_assignment RESTART IDENTITY;
TRUNCATE TABLE employee RESTART IDENTITY;
TRUNCATE TABLE person RESTART IDENTITY;
TRUNCATE TABLE position RESTART IDENTITY;
TRUNCATE TABLE structure_element RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
